# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 09:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_full_name', models.CharField(max_length=50, verbose_name='Driver Full Name')),
                ('driver_nickname', models.CharField(max_length=50, verbose_name='Driver Nickname')),
                ('driver_contact_no', models.IntegerField(verbose_name='Driver Contact No')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('store_address1', models.CharField(max_length=100, verbose_name='Store Address Line 1')),
                ('store_address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Address Line 2')),
                ('store_postal', models.IntegerField(verbose_name='Store Postal Code')),
                ('store_contact_no', models.IntegerField(verbose_name='Store Contact No')),
                ('store_district_area', models.CharField(max_length=2, verbose_name='Store District and Area')),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Driver', verbose_name='Driver Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Request')),
                ('request_fulfilled_date', models.DateTimeField(blank=True, null=True, verbose_name='Request Fulfilled Date')),
                ('request_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('request_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requesting_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Store', verbose_name='Requesting Store')),
            ],
        ),
    ]
