# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_wechat_id',
            field=models.CharField(default='none', max_length=50, verbose_name='Driver WeChat ID'),
        ),
    ]
