# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_driver_driver_wechat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Driver', verbose_name='Assigned Driver'),
        ),
    ]
