# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_storerequest_assigned_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver Nickname'),
        ),
    ]
