# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 04:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170816_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]')]),
        ),
    ]
