# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170817_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_contact_no',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='8 digit phone number only', regex='^([0-9]{8})$')], verbose_name='Store Contact No'),
        ),
    ]
