# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170817_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequest',
            name='request_invoice_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Invoice No'),
        ),
    ]
